import { StatusPill } from "@/components/status-pill";

export function DraftStatusBanner({ status, modelName }: { status: string; modelName?: string }) {
  return (
    <div className="flex items-center justify-between rounded-2xl border border-blue-200 bg-blue-50 px-4 py-3">
      <div>
        <p className="text-sm font-medium text-blue-900">Draft status: {status.replaceAll("_", " ")}</p>
        {modelName ? <p className="text-xs text-blue-700">Generated by {modelName}</p> : null}
      </div>
      <StatusPill value={status} />
    </div>
  );
}
