def serialize_approval(approval) -> dict:
    return {
        "id": str(approval.id),
        "status": approval.status,
        "action_type": approval.action_type,
        "entity_type": approval.entity_type,
        "entity_id": str(approval.entity_id),
        "workflow_run_id": str(approval.workflow_run_id) if approval.workflow_run_id else None,
        "agent_run_id": str(approval.agent_run_id) if approval.agent_run_id else None,
        "proposed_action_json": approval.proposed_action_json,
        "reasoning": approval.reasoning,
        "review_notes": approval.review_notes,
        "execution_status": approval.execution_status,
        "execution_error": approval.execution_error,
        "trace_id": approval.trace_id,
        "failure_class": approval.failure_class,
        "failure_code": approval.failure_code,
        "last_error_at": approval.last_error_at.isoformat() if approval.last_error_at else None,
        "next_retry_at": approval.next_retry_at.isoformat() if approval.next_retry_at else None,
        "max_retries": approval.max_retries,
        "attempt_count": approval.attempt_count,
        "retry_count": approval.retry_count,
        "expires_at": approval.expires_at.isoformat(),
        "created_at": approval.created_at.isoformat(),
        "updated_at": approval.updated_at.isoformat(),
    }

